### ISSUE TITLE
dosent work

### ISSUE THREAD

**Issue by Nuclearpotato69** [middleclicker/ZealotSniper#1]
ik its old but it does not work for me idk why heres the error:

C:\Users\user\Downloads\ZealotSniper-main\ZealotSniper-main>run.py
No sympy found
Traceback (most recent call last):
  File "C:\Users\user\Downloads\ZealotSniper-main\ZealotSniper-main\run.py", line 1, in <module>
    import torch
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\__init__.py", line 1465, in <module>
    from . import _meta_registrations
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_meta_registrations.py", line 7, in <module>
    from torch._decomp import _add_op_to_registry, global_decomposition_table, meta_table
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_decomp\__init__.py", line 169, in <module>
    import torch._decomp.decompositions
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_decomp\decompositions.py", line 10, in <module>
    import torch._prims as prims
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_prims\__init__.py", line 33, in <module>
    from torch._subclasses.fake_tensor import FakeTensor, FakeTensorMode
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_subclasses\__init__.py", line 3, in <module>
    from torch._subclasses.fake_tensor import (
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_subclasses\fake_tensor.py", line 13, in <module>
    from torch._guards import Source
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_guards.py", line 78, in <module>
    class ShapeGuard(NamedTuple):
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch-2.0.1-py3.11-win-amd64.egg\torch\_guards.py", line 79, in ShapeGuard
    expr: sympy.Expr
          ^^^^^
NameError: name 'sympy' is not defined

**Comment by middleclicker** [comment]
It's a problem with your pytorch. Have a look at this reply

https://github.com/pytorch/vision/issues/7034#issuecomment-1412546840
